--- # Conditional Based PlayBook
-  hosts: Webserver
   remote_user: centos
   become: yes
   become_method: sudo
   connection: ssh
   gather_facts: yes
   tasks: 
   - name: If Os is RedHat install Http
     yum:
         name: httpd
         state: present
     when: ansible_os_family == 'RedHat'
